---
title: "2017-annual-review"
author: "Oskar Flygare"
date: '2017-12-30'
output:
  html_document:
    toc: yes
    toc_depth: '3'
    code_folding: show
    theme: flatly

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load packages

```{r packages, message=FALSE, warning=FALSE}

library(tidyverse)
library(plyr)
library(googlesheets)
library(stringr)

```

# Read data

```{r read-data, message=FALSE, warning=FALSE}
review_2017 <- gs_title("2017 review")

q1 <- review_2017 %>%
  gs_read(ws = "Q1",
          range = "B15:E21")

q2 <- review_2017 %>%
  gs_read(ws = "Q2",
          range = "B12:E18")

q3 <- review_2017 %>%
  gs_read(ws = "Q3",
          range = "B11:E17")

q4 <- review_2017 %>%
  gs_read(ws = "Q4",
          range = "B11:E17")
```

# Merge and wrangle data

```{r merge-wrangle}
df_2017 <- join_all(
  list(q1, q2, q3, q4),
  by = "Goal",
  type = "full") %>%
  gather(month, value, -Goal)

df_2017$value <- str_replace_all(df_2017$value, "%", "")
df_2017$value <- as.integer(df_2017$value)

df_2017 <- mutate(df_2017, month = fct_recode(month,
                                                  "1" = "January",
                                                  "2" = "February",
                                                  "3" = "March",
                                                  "4" = "April",
                                                  "5" = "May",
                                                  "6" = "June",
                                                  "7" = "July",
                                                  "8" = "August",
                                                  "9" = "September",
                                                  "10" = "October",
                                                  "11" = "November",
                                                  "12" = "December"))
df_2017 <- df_2017 %>%
  mutate(month = factor(month, levels = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)))
  
```

# Plotting

```{r plot}
lineplot <- df_2017 %>%
  filter(!Goal %in% "Top 3") %>%
  ggplot(aes(x = month, y = value, group = Goal)) + geom_point() + geom_line(group = 1) +
  labs(title = "Goal fulfillment",
       subtitle = "Month by month 2017",
       y = "Percent",
       x = " ") +
  theme_classic() +
  facet_grid(. ~ Goal)

lineplot

ggsave("goals2017.png", width = 5, height = 3)
```
